### ISSUE TITLE
Packages for Ubuntu 22.10

### ISSUE THREAD

**Issue by mathieujobin** [DexterMagnific/QSvgStyle#12]
Hi, 

would be great if you could push .deb packages for jammy 22.04 and kinetic 22.10

Thanks

**Comment by DexterMagnific** [comment]
Hi. Unfortunately I don't know how to do it.

**Comment by mathieujobin** [comment]
I will try to find the time to help... I'd like this to become easier for me as well...

https://packaging.ubuntu.com/html/index.html

Are you also interested making dynamic window decorations for kwin?

**Comment by DexterMagnific** [comment]
Not at this time. I'd like to stick to Qt only code.

**Comment by mathieujobin** [comment]
Ok, no problem
