### ISSUE TITLE
Change the text style

### ISSUE THREAD

**Issue by salomonthewise** [DexterMagnific/QSvgStyle#3]
Hi, would it be possible to change the text style of an element? eg making all menuitems or pushbuttons use bold text?

**Comment by DexterMagnific** [comment]
Hi,

I'm currently working on an improvement that will make the colors (foreground/background) customizable. I will see if changing text style is something popular.

**Comment by ghost** [comment]
would be great to have it so I could port my gtk theme to this engine

**Comment by DexterMagnific** [comment]
Thank you for your interest in QSvgStyle. I'll do my best to make that change. Meanwhile, please proceed with porting your theme, I'll be happy to hear about your work, and please report any issues.

**Comment by DexterMagnific** [comment]
Hello @sixsixfive,

I'm happy to inform you that your request has  been implemented in latest (5c9eb47) commit.
