### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ghost** [DexterMagnific/QSvgStyle#4]
Hi,

* is it possible to disable that blinking focus stuff?

* How does a palette work? are the similar to palettes created by qt5ct(eg: https://github.com/sixsixfive/DarK/blob/master/Extras/App_themes/Qt5ct/colors/DarK.conf)

* where do i put theme specifc tweaks eg: scrollbar size etc? can i append them to the normal *.cfg file

PPS: that qsvgstylebuilder is terrible to use, any chance that the quantumstyle inkscape entensions get ported?

**Comment by DexterMagnific** [comment]
Hi,

Thank you for your interest in QSvgStyle.

- Blinking focus overlay will be removed in the next release
- Palette support is incomplete. You can only change foreground and background in a specific .pal file. But QSvgStyle supports system color schemes. Just change the system color scheme and the colors will be applied to the theme. Use QSvgThemeManager to set the palette to "<system>".
- Use QSvgThemeManager to set engine specific settings. They are not part of the theme itself, but part of the engine.

Regarding QSvgThemeBuilder, I'm very surprised it is hard to use. Now It has an SVG generator that generates SVG elements better that the legacy inkscape extensions. What are you missing ?

**Comment by ghost** [comment]
>Use QSvgThemeManager to set engine specific settings. They are not part of the theme itself, but part of the engine.

sorry but that is nonsense for distributing themes - the theme should have a default look on all devices and not look differently on all machines

>Regarding QSvgThemeBuilder, I'm very surprised it is hard to use. Now It has an SVG generator that generates SVG elements better that the legacy inkscape extensions. What are you missing ?

sure but you need 2 apps open inkscape whith the whole style and the svg generator. I liked the way quantum style worked one familiar app you could work with to create a theme

**Comment by DexterMagnific** [comment]
Regarding the engine vs. theme specific settings, you're right. I'll move them.
Regarding the two apps open, the idea is that while you're editing the theme in Inkscape, you see the live preview on QSvhThemeBuilder. So opening the two apps becomes mandatory.

The reason I moved to SVG generator are my very limited Python skills. Inkscape extensions have to written in Python.

**Comment by DexterMagnific** [comment]
Dear @sixsixfive,

The specific settings have been moved back to theme config in the latest release.

Regards,
dexter
