### ISSUE TITLE
unable to compile

### ISSUE THREAD

**Issue by dagodemon42** [DexterMagnific/QSvgStyle#7]
cd styleconfig/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/keith/QSvgStyle/styleconfig/styleconfig.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/keith/QSvgStyle/styleconfig'
make[1]: Nothing to be done for 'first'.
make[1]: Leaving directory '/home/keith/QSvgStyle/styleconfig'
cd style/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/keith/QSvgStyle/style/style.pro -o Makefile ) && make -f Makefile 
make[1]: Entering directory '/home/keith/QSvgStyle/style'
g++ -c -m64 -pipe -O2 -D_REENTRANT -Wall -W -fPIC -DQT_NO_DEBUG -DQT_PLUGIN -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I. -I../styleconfig -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -o QSvgThemableStyle.o QSvgThemableStyle.cpp
QSvgThemableStyle.cpp: In member function ‘virtual void QSvgThemableStyle::drawComplexControl(QStyle::ComplexControl, const QStyleOptionComplex*, QPainter*, const QWidget*) const’:
QSvgThemableStyle.cpp:2951:39: error: ‘PM_TitleBarButtonSize’ was not declared in this scope
         const int btnsz = pixelMetric(PM_TitleBarButtonSize,opt,widget);
                                       ^~~~~~~~~~~~~~~~~~~~~
QSvgThemableStyle.cpp:2952:40: error: ‘PM_TitleBarButtonIconSize’ was not declared in this scope
         const int iconsz = pixelMetric(PM_TitleBarButtonIconSize,opt,widget);
                                        ^~~~~~~~~~~~~~~~~~~~~~~~~
QSvgThemableStyle.cpp: In member function ‘virtual int QSvgThemableStyle::pixelMetric(QStyle::PixelMetric, const QStyleOption*, const QWidget*) const’:
QSvgThemableStyle.cpp:3175:10: error: ‘PM_TitleBarButtonIconSize’ was not declared in this scope
     case PM_TitleBarButtonIconSize : return 32;
          ^~~~~~~~~~~~~~~~~~~~~~~~~
QSvgThemableStyle.cpp:3176:10: error: ‘PM_TitleBarButtonSize’ was not declared in this scope
     case PM_TitleBarButtonSize :
          ^~~~~~~~~~~~~~~~~~~~~
QSvgThemableStyle.cpp: In member function ‘virtual QRect QSvgThemableStyle::subControlRect(QStyle::ComplexControl, const QStyleOptionComplex*, QStyle::SubControl, const QWidget*) const’:
QSvgThemableStyle.cpp:4447:36: error: ‘PM_TitleBarButtonSize’ was not declared in this scope
         const int bw = pixelMetric(PM_TitleBarButtonSize); // button width
                                    ^~~~~~~~~~~~~~~~~~~~~
QSvgThemableStyle.cpp:4472:39: error: ‘PM_TitleBarButtonIconSize’ was not declared in this scope
           sysBtn.setWidth(pixelMetric(PM_TitleBarButtonIconSize));
                                       ^~~~~~~~~~~~~~~~~~~~~~~~~
QSvgThemableStyle.cpp: In member function ‘virtual QIcon QSvgThemableStyle::standardIcon(QStyle::StandardPixmap, const QStyleOption*, const QWidget*) const’:
QSvgThemableStyle.cpp:4604:24: error: ‘PM_TitleBarButtonSize’ was not declared in this scope
       sz = pixelMetric(PM_TitleBarButtonSize);
                        ^~~~~~~~~~~~~~~~~~~~~
Makefile:452: recipe for target 'QSvgThemableStyle.o' failed
make[1]: *** [QSvgThemableStyle.o] Error 1
make[1]: Leaving directory '/home/keith/QSvgStyle/style'
Makefile:90: recipe for target 'sub-style-make_first-ordered' failed
make: *** [sub-style-make_first-ordered] Error 2

**Comment by DexterMagnific** [comment]
Hello,

please tell me which Qt version you are using.

**Comment by dagodemon42** [comment]
distro is devuan kde. QT is 5.7.1

**Comment by DexterMagnific** [comment]
According to the Qt doc, this enum has been introduced in Qt 5.8.
ref:  [http://doc.qt.io/qt-5/qstyle.html](http://doc.qt.io/qt-5/qstyle.html)
