### ISSUE TITLE
How does the coloring works?

### ISSUE THREAD

**Issue by sixsixfive** [DexterMagnific/QSvgStyle#9]
So i put all the palette lines under general and let all elements inherit general but the window is still uncolored.

are the colors are in R,G,B,A or in HSL? or does it only support color for elements?

![Screenshot at 2020-01-26 13-13-29](https://user-images.githubusercontent.com/40307321/73135053-3df77900-403e-11ea-8aa9-fc699e800663.png)

**Comment by DexterMagnific** [comment]
The [General] section is a bug and does not impact elements. Please remove it. Please move your palette to (for example) [PushButton] and make other elements inherit from it.

**Comment by sixsixfive** [comment]
OK I have tried Window, and Pushbutton both had no effect. I recompiled the style to make sure nothing has been altered by an updated Qt version :(

Did I something wrong? Also I don't use the theme builder just plain text editing.
[ceres-new.tar.gz](https://github.com/DexterMagnific/QSvgStyle/files/4118592/ceres-new.tar.gz)

**Comment by DexterMagnific** [comment]
I tried your theme and colors work (under the theme builder). Just noticed this inconsistency: remove that PushButton inherits from itself.

**Comment by DexterMagnific** [comment]
Here is a screen record:

[vokoscreen-2020-01-28_09-58-39.zip](https://github.com/DexterMagnific/QSvgStyle/files/4121522/vokoscreen-2020-01-28_09-58-39.zip)

**Comment by sixsixfive** [comment]
ok i removed now everything form the file and replaced all bg colors with #0000ffff and all fg colors with #ff0000ff

now everything should be colored in blue with green font, but the window still stays grey and the listviews/treeviews/combobox lists stay white. some fonts are still black (eg spinbuttons or listview)

Also some colors seem to be translucent since all elements should have the same blue(EDIT: meh - forget that i found that specific.palette.intensity needs to be set to 255)

```
[PushButton]
frame=false
indicator.element=arrow
indicator.size=7
interior=true
palette.default.bg="0,0,255,255"
palette.default.fg="0,255,0,255"
palette.disabled-toggled.bg="0,0,255,255"
palette.disabled-toggled.fg="0,255,0,255"
palette.disabled.bg="0,0,255,255"
palette.disabled.fg="0,255,0,255"
palette.focused.bg="0,0,255,255"
palette.focused.fg="0,255,0,255"
palette.hovered.bg="0,0,255,255"
palette.hovered.fg="0,255,0,255"
palette.normal.bg="0,0,255,255"
palette.normal.fg="0,255,0,255"
palette.pressed.bg="0,0,255,255"
palette.pressed.fg="0,255,0,255"
palette.toggled.bg="0,0,255,255"
palette.toggled.fg="0,255,0,255"

[General]
frame=false
interior=false
element.inherits=PushButton

[CheckBox]
element.inherits=PushButton
frame=true
frame.element=radio-bg
frame.width=2
indicator.element=checkbox
indicator.size=15
interior.element=radio-bg

[ComboBox]
element.inherits=PushButton

[Dial]
element.inherits=PushButton
[DockWidget]
element.inherits=PushButton

[DockWidgetContents]
element.inherits=PushButton

[DockWidgetTitle]
element.inherits=PushButton

[Frame]
element.inherits=PushButton

[%General]
author=Said Lankri
comment=blah
keywords=QSvgStyle
name=Ceres-new
variant=Light

[GroupBoxContents]
element.inherits=PushButton

[GroupBoxTitle]
element.inherits=PushButton

[Header]
element.inherits=PushButton

[LineEdit]
element.inherits=PushButton

[Menu]
element.inherits=PushButton

[MenuBar]
element.inherits=PushButton

[MenuBarItem]
element.inherits=PushButton

[MenuItem]
element.inherits=PushButton

[ProgressBar]
element.inherits=PushButton

[RadioButton]
element.inherits=PushButton
frame.element=radio-bg
frame.width=2
indicator.element=radio
indicator.size=15
interior.element=radio-bg

[RubberBand]
element.inherits=PushButton

[ScrollBarButton]
element.inherits=PushButton

[ScrollBarCursor]
element.inherits=PushButton

[ScrollBarGroove]
element.inherits=PushButton

[Slider]
element.inherits=PushButton

[SpinBox]
element.inherits=PushButton

[Splitter]
element.inherits=PushButton

[StatusBar]
element.inherits=PushButton


[TabBarBase]
element.inherits=PushButton

[TabBarTab]
element.inherits=PushButton

[TabContents]
element.inherits=PushButton

[ToolBar]
element.inherits=PushButton


[ToolBox]
element.inherits=PushButton

[ToolButton]
element.inherits=PushButton

[Tooltip]
element.inherits=PushButton

[Tweaks]
specific.button.usecapsule=1
specific.dock.handle.width=20
specific.dock.separator.size=8
specific.dropdown.size=20
specific.layoutmargins.bottom=4
specific.layoutmargins.hspace=2
specific.layoutmargins.left=4
specific.layoutmargins.right=4
specific.layoutmargins.top=4
specific.layoutmargins.vspace=2
specific.menu.forcetearoff=0
specific.menu.separator.height=2
specific.menu.tearoff.height=4
specific.menu.usecapsule=0
specific.menubar.hspace=10
specific.menubar.space=2
specific.palette.3dframes=false
specific.palette.intensity=100
specific.palette.type=0
specific.progressbar.busy.full.variant=1
specific.progressbar.busy.variant=2
specific.progressbar.chunk.width=14
specific.progressbar.thin.minheight=12
specific.progressbar.variant=1
specific.radiocheckbox.label.tispace=5
specific.scrollbar.slider.area=0
specific.scrollbar.slider.minsize=32
specific.scrollbar.thickness=10
specific.scrollbar.variant=1
specific.slider.cursor.size=16
specific.slider.thickness=2
specific.slider.ticks.offset=1
specific.spinbox.variant=2
specific.tab.variant=2
specific.toolbar.extension.width=20
specific.toolbar.handle.width=8
specific.toolbar.icon.size=24
specific.toolbar.itemmargin=2
specific.toolbar.separator.width=2
specific.toolbar.space=2

[ViewItem]
element.inherits=PushButton

[Window]
element.inherits=PushButton
```
![Screenshot at 2020-01-28 16-50-13](https://user-images.githubusercontent.com/40307321/73280211-82c21200-41ee-11ea-92d7-e7531c46b660.png)
![Screenshot at 2020-01-28 16-50-37](https://user-images.githubusercontent.com/40307321/73280212-82c21200-41ee-11ea-8dfa-9e9f07edd5e0.png)
![Screenshot at 2020-01-28 16-51-01](https://user-images.githubusercontent.com/40307321/73280213-835aa880-41ee-11ea-9755-2311502984b6.png)
![Screenshot at 2020-01-28 16-51-18](https://user-images.githubusercontent.com/40307321/73280215-835aa880-41ee-11ea-9f18-6436457407e2.png)

**Comment by DexterMagnific** [comment]
Ok I see your problem.

"windows" and "tree views/combo box lists" are "blank" areas filled by the widget itself using QPalette::Window or QPalette::Base respectively. The style does not get called for this kind of areas. So setting a color like fg and bg inside the theme won't work.

If you want to set a custom color for these areas, you have to change the current color scheme in your settings.

QSvgStyle coloring can only happen for elements that it draws (see list in QSvgThemeBuilder) like tree view items (but not tree view "blank" areas). Note that "tab widget areas" are drawn by the style so we can apply coloring on them.

Sorry that you can't achieve this using theming.

**Comment by DexterMagnific** [comment]
Regarding the editable spin box font color, I will look into it.

**Comment by sixsixfive** [comment]
> Sorry that you can't achieve this using theming.

OK I can recolor them with qtconfig that is not the ideal solution but it works.
